// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinFormsApp2.Data;

#nullable disable

namespace WinFormsApp2.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WinFormsApp2.Models.MixedZoneSteelGroup", b =>
                {
                    b.Property<int>("Fsg_GroupId")
                        .HasColumnType("int");

                    b.Property<int>("Fsg_Row")
                        .HasColumnType("int");

                    b.Property<int?>("Fsg_MixedZoneSteelGroup")
                        .HasColumnType("int");

                    b.HasKey("Fsg_GroupId", "Fsg_Row");

                    b.ToTable("TMixedZoneSteelGroup");
                });

            modelBuilder.Entity("WinFormsApp2.Models.PivotResult", b =>
                {
                    b.Property<int>("Fsg_GroupId")
                        .HasColumnType("int");

                    b.Property<int?>("Row1")
                        .HasColumnType("int");

                    b.Property<int?>("Row2")
                        .HasColumnType("int");

                    b.Property<int?>("Row3")
                        .HasColumnType("int");

                    b.Property<int?>("Row4")
                        .HasColumnType("int");

                    b.Property<int?>("Row5")
                        .HasColumnType("int");

                    b.ToTable("PivotResults");
                });
#pragma warning restore 612, 618
        }
    }
}
